export const GET_FILTERED_PRODUCTS = 'CATEGORY/GET_FILTERED_PRODUCTS'
export const GET_FILTERED_PRODUCTS_ERROR = 'CATEGORY/GET_FILTERED_PRODUCTS_ERROR'
export const GET_FILTERED_PRODUCTS_SUCCESS = 'CATEGORY/GET_FILTERED_PRODUCTS_SUCCESS'
export const GET_FILTERED_PRODUCTS_LOADING = 'CATEGORY/GET_FILTERED_PRODUCTS_LOADING'