export const offerCarousel=[
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-tns-advanced-serum-1oz/12596429.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12596429-3594871019700125.jpg",
          "productBlock_productName": "SkinMedica TNS Advanced+ Serum (1 oz.)",
          "visually-hidden": "4.58 Stars 301 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.58,
          "productBlock_reviewCount": 301,
          "productBlock_rrpValue": "$295.00",
          "productBlock_priceValue": "$236.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-tns-eye-repair/11289683.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289683-2074871019620370.jpg",
          "productBlock_productName": "SkinMedica TNS Eye Repair (0.5 oz.)",
          "visually-hidden": "4.54 Stars 403 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.54,
          "productBlock_reviewCount": 403,
          "productBlock_rrpValue": "$106.00",
          "productBlock_priceValue": "$84.80"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-firm-and-tone-lotion-6-oz/13180872.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13180872-1214888074076647.jpg",
          "productBlock_productName": "SkinMedica Firm and Tone Lotion 6 oz",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_rrpValue": "$165.00",
          "productBlock_priceValue": "$132.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-ha5-rejuvenating-hydrator/11290631.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11290631-5864870995720591.jpg",
          "productBlock_productName": "SkinMedica HA5 Rejuvenating Hydrator (2 oz.)",
          "visually-hidden": "4.71 Stars 556 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.71,
          "productBlock_reviewCount": 556,
          "productBlock_rrpValue": "$184.00",
          "productBlock_priceValue": "$147.20"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-retinol-complex-1.0/11289678.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289678-1494870995623922.jpg",
          "productBlock_productName": "SkinMedica Age Defense Retinol Complex 1.0 (1 fl. oz.)",
          "visually-hidden": "4.85 Stars 301 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.85,
          "productBlock_reviewCount": 301,
          "productBlock_rrpValue": "$96.00",
          "productBlock_priceValue": "$76.80"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-lytera-2.0-pigment-correcting-serum/11396212.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11396212-1194870995675144.jpg",
          "productBlock_productName": "SkinMedica Lytera 2.0 Pigment Correcting Serum (2 oz.)",
          "visually-hidden": "4.41 Stars 307 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.41,
          "productBlock_reviewCount": 307,
          "productBlock_rrpValue": "$160.00",
          "productBlock_priceValue": "$128.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-retinol-complex-0.5/11289677.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289677-3634870995577404.jpg",
          "productBlock_productName": "SkinMedica Age Defense Retinol Complex 0.5 (1 fl. oz.)",
          "visually-hidden": "4.78 Stars 285 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.78,
          "productBlock_reviewCount": 285,
          "productBlock_rrpValue": "$80.00",
          "productBlock_priceValue": "$64.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-rejuvenative-moisturizer/11289673.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289673-4514872069791922.jpg",
          "productBlock_productName": "SkinMedica Rejuvenative Moisturizer (2 oz.)",
          "visually-hidden": "4.68 Stars 230 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.68,
          "productBlock_reviewCount": 230,
          "productBlock_rrpValue": "$60.00",
          "productBlock_priceValue": "$48.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-retinol-complex-0.25/11289676.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289676-6714870996215309.jpg",
          "productBlock_productName": "SkinMedica Age Defense Retinol Complex .25 (1 fl. oz.)",
          "visually-hidden": "4.81 Stars 234 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.81,
          "productBlock_reviewCount": 234,
          "productBlock_rrpValue": "$64.00",
          "productBlock_priceValue": "$51.20"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-facial-cleanser/11289661.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp/productimg/1600/1600/11289661-1794453993724103.jpg",
          "productBlock_productName": "SkinMedica Facial Cleanser",
          "visually-hidden": "4.67 Stars 12 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.67,
          "productBlock_reviewCount": 12,
          "productBlock_rrpValue": "$40.00",
          "productBlock_priceValue": "$32.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-instant-bright-eye-cream-5-oz/12378444.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12378444-2084870995827076.jpg",
          "productBlock_productName": "SkinMedica Instant Bright Eye Cream (0.5 oz.)",
          "visually-hidden": "4.57 Stars 114 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.57,
          "productBlock_reviewCount": 114,
          "productBlock_rrpValue": "$92.00",
          "productBlock_priceValue": "$73.60"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-dermal-repair-cream/11289659.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289659-3844870996065429.jpg",
          "productBlock_productName": "SkinMedica Dermal Repair Cream (1.7 oz.)",
          "visually-hidden": "4.74 Stars 225 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.74,
          "productBlock_reviewCount": 225,
          "productBlock_rrpValue": "$134.00",
          "productBlock_priceValue": "$107.20"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-tns-ceramide-treatment-cream/11289681.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289681-1484871019698619.jpg",
          "productBlock_productName": "SkinMedica TNS Ceramide Treatment Cream (2 oz.)",
          "visually-hidden": "4.73 Stars 200 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.73,
          "productBlock_reviewCount": 200,
          "productBlock_rrpValue": "$72.00",
          "productBlock_priceValue": "$57.60"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-ultra-sheer-moisturizer/11289690.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289690-1794871029936020.jpg",
          "productBlock_productName": "SkinMedica Ultra Sheer Moisturizer (2 fl. oz.)",
          "visually-hidden": "4.81 Stars 157 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.81,
          "productBlock_reviewCount": 157,
          "productBlock_rrpValue": "$60.00",
          "productBlock_priceValue": "$48.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-instant-bright-eye-mask-6-pack/12455153.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12455153-5734870995929202.jpg",
          "productBlock_productName": "SkinMedica Instant Bright Eye Mask (6 piece)",
          "visually-hidden": "4.22 Stars 45 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.22,
          "productBlock_reviewCount": 45,
          "productBlock_rrpValue": "$50.00",
          "productBlock_priceValue": "$40.00"
        }
       ];
export const giftSetCarousel=[
        {
          "productBlock_link href": "https://www.dermstore.com/best-of-dermstore-problem-soultion-anti-aging-regimen/13190899.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13190899-1224883933404728.jpg",
          "productBlock_productName": "Best of Dermstore Problem Solution: Anti-Aging Regimen ($245 Value)",
          "papBanner_text": "Up to 65% Savings on Best of Dermstore",
          "papPopup_text": "Save up to 65% on Best of Dermstore kits. While stock lasts.",
          "papPopup_link": "SHOP ALL",
          "papPopup_link href": "https://www.dermstore.com/brands/best-of-dermstore.list",
          "visually-hidden": "4.68 Stars 53 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.68,
          "productBlock_reviewCount": 53,
          "productBlock_priceValue": "$65.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/ghd-platinum-styler-1-flat-iron-grand-luxe-collection/13934554.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13934554-7014985567865774.jpg",
          "productBlock_productName": "ghd Platinum+ Styler - 1\" Flat Iron, Grand-Luxe Collection (Worth $319.00)",
          "papBanner_text": "New Arrival",
          "papPopup_text": "Shop new arrivals to discover the latest in beauty, skin and hair care and stock up on seasonal must-haves and everyday essentials.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/new-arrivals.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$279.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/t3-airebrush-duo/13222916.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13222916-3644914880619826.jpg",
          "productBlock_productName": "T3 AireBrush Duo",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "5.0 Stars 2 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 2,
          "productBlock_priceValue": "$189.99",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/dr.-loretta-the-essentials-set/12746891.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12746891-7394837306723863.jpg",
          "productBlock_productName": "Dr. Loretta The Essentials Regimen Set (4 piece - $180 Value)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "5.0 Stars 1 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 1,
          "productBlock_priceValue": "$135.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/elemis-dynamic-resurfacing-the-radiant-collection/13899714.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13899714-1864998013410465.jpg",
          "productBlock_productName": "Elemis Dynamic Resurfacing The Radiant Collection (Worth $112.00)",
          "papBanner_text": "Save 25%",
          "papPopup_text": "Save 25% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/25.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$61.50",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$82.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/alpha-h-midnight-r-and-r-kit/13948123.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13948123-1614995414843501.jpg",
          "productBlock_productName": "Alpha-H Midnight R and R Kit (Worth $85.00)",
          "papBanner_text": "Save 30%",
          "papPopup_text": "Save 30% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/30.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$38.50",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$55.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/ghd-glide-smoothing-hot-brush-grand-luxe-collection/13934557.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13934557-1684985568542106.jpg",
          "productBlock_productName": "ghd Glide Smoothing Hot Brush - Grand-Luxe Collection (Worth $209.00)",
          "papBanner_text": "New Arrival",
          "papPopup_text": "Shop new arrivals to discover the latest in beauty, skin and hair care and stock up on seasonal must-haves and everyday essentials.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/new-arrivals.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$169.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/lancer-skincare-and-cleanse-duo/13971254.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13971254-9984996753970325.jpg",
          "productBlock_productName": "Lancer Skincare and Cleanse Duo",
          "papBanner_text": "Additional 10% off sale products with code EXTRA10",
          "papPopup_text": "Last Chance sale ends 1/31/23 at 11:59 p.m. PT. Receive an extra 10% off already markdown products. Valid on participating products only. Select SHOP NOW to view participating products.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/shop/last-chance-sale.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$31.20",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$52.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/alpha-h-icons-kit/13948122.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13948122-1254995414344760.jpg",
          "productBlock_productName": "Alpha-H Icons Kit (Worth $116.00)",
          "papBanner_text": "Save 30%",
          "papPopup_text": "Save 30% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/30.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$55.30",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$79.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/elemis-cleanse-and-hydrate-a-magnificent-pro-collagen-tale-set/13899712.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13899712-1784998013071582.jpg",
          "productBlock_productName": "Elemis Cleanse and Hydrate a Magnificent Pro-Collagen Tale Set (Worth $165.00)",
          "papBanner_text": "Save 25%",
          "papPopup_text": "Save 25% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/25.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$82.50",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$110.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/olaplex-shampoo-and-conditioner-bundle/12658441.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12658441-1014951908068217.jpg",
          "productBlock_productName": "Olaplex Shampoo and Conditioner Bundle",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.75 Stars 12 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.75,
          "productBlock_reviewCount": 12,
          "productBlock_priceValue": "$60.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/beauty-box/best-of-dermstore-the-necessities-kit-431-value/13812005.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13812005-4724980887145978.jpg",
          "productBlock_productName": "Best of Dermstore The Necessities Kit - $431 Value",
          "papBanner_text": "Up to 65% Savings on Best of Dermstore",
          "papPopup_text": "Save up to 65% on Best of Dermstore kits. While stock lasts.",
          "papPopup_link": "SHOP ALL",
          "papPopup_link href": "https://www.dermstore.com/brands/best-of-dermstore.list",
          "visually-hidden": "5.0 Stars 8 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 8,
          "productBlock_priceValue": "$100.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/revive-the-new-renewal-collection-2-piece-full-size-holiday-set/13950623.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13950623-8564993320798504.jpg",
          "productBlock_productName": "RéVive The New RéNewal Collection 2 Piece Full Size Holiday Set (Worth $345.00)",
          "papBanner_text": "Save 25%",
          "papPopup_text": "Save 25% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/25.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$187.50",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$250.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/living-proof-brilliantly-the-best-set/13927352.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13927352-8624981956350304.jpg",
          "productBlock_productName": "Living Proof Brilliantly the Best Set (Worth $62.00)",
          "papBanner_text": "Save 20%",
          "papPopup_text": "Save 20% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/20.list",
          "visually-hidden": "5.0 Stars 1 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 1,
          "productBlock_priceValue": "$31.20",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$39.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/olaplex-bond-maintenance-holiday-kit-jumbo-no.3-no.4-no.5/13903618.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13903618-6054979846869767.jpg",
          "productBlock_productName": "Olaplex Bond Maintenance Holiday Kit - Jumbo No.3, No.4, No.5 (Worth $137.00)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$99.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/glytone-kp-kit/11287686.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11287686-1724868437331874.jpg",
          "productBlock_productName": "Glytone KP Kit (3 piece - $76 Value)",
          "papBanner_text": "$19 Glytone Gift",
          "papPopup_text": "Receive Glytone's 30th Anniversary Best Sellers ($19 value) when you spend $75 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/glytone.list",
          "visually-hidden": "4.54 Stars 157 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.54,
          "productBlock_reviewCount": 157,
          "productBlock_priceValue": "$69.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/sunday-riley-mini-power-couple-travel-kit-2-piece/12902813.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12902813-1694871307916944.jpg",
          "productBlock_productName": "Sunday Riley Mini Power Couple Travel Kit (2 piece - $41 Value)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.9 Stars 29 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.9,
          "productBlock_reviewCount": 29,
          "productBlock_priceValue": "$28.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/virtue-full-bundle/13888005.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13888005-8024975459777782.jpg",
          "productBlock_productName": "VIRTUE Full Bundle",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$82.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        }
       ];
export const exclusiveCarousel=[
        {
          "productBlock_link href": "https://www.dermstore.com/living-proof-dermstore-exclusive-jumbo-phd-dry-shampoo-duo-15-oz./13175696.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13175696-1284889422857909.jpg",
          "productBlock_productName": "Living Proof Dermstore Exclusive Jumbo PhD Dry Shampoo Duo 15 oz. (Worth $86.00)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "4.0 Stars 9 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4,
          "productBlock_reviewCount": 9,
          "productBlock_priceValue": "$58.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/nuface-dermstore-exclusive-trinity-ele-kit-and-accessories-bundle/13761887.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13761887-1754965608525076.jpg",
          "productBlock_productName": "NuFACE Dermstore Exclusive Trinity ELE Kit and Accessories Bundle ($520 Value)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$449.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/eltamd-uv-glow-broad-spectrum-spf36-untinted-serum-1.7-oz/12852428.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12852428-8454876441353615.jpg",
          "productBlock_productName": "EltaMD Dermstore Exclusive UV Glow Broad-Spectrum SPF 36 1.7 oz. - Untinted",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "2.66 Stars 38 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 2.66,
          "productBlock_reviewCount": 38,
          "productBlock_priceValue": "$38.50",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/glo-skin-beauty-dermstore-exclusive-bio-renew-egf-cream-and-egf-drops-duo/13920976.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13920976-2644983786116838.jpg",
          "productBlock_productName": "Glo Skin Beauty Dermstore Exclusive Bio-Renew EGF Cream and EGF Drops Duo",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "5.0 Stars 5 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 5,
          "productBlock_priceValue": "$175.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinceuticals-dermstore-exclusive-top-sellers-vault-kit/13997566.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13997566-1855001922340772.jpg",
          "productBlock_productName": "Dermstore Exclusive SkinCeuticals Top Sellers Vault Kit (Worth $516.00)",
          "papBanner_text": "Limited Edition Bundle",
          "papPopup_text": "Treat yourself to one of our limited edition SkinCeuticals bundles.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/skinceuticals.list",
          "visually-hidden": "5.0 Stars 1 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 1,
          "productBlock_priceValue": "$438.60",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$516.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/eltamd-dermstore-exclusive-cleanse-and-protect-kit/13338895.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13338895-4124905796292901.jpg",
          "productBlock_productName": "EltaMD Dermstore Exclusive Cleanse and Protect Kit",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "5.0 Stars 7 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 7,
          "productBlock_priceValue": "$58.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/dermstore-exclusive-scalp-treatment-kit-3-piece/12707050.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12707050-4604866389386266.jpg",
          "productBlock_productName": "Dermstore Exclusive Scalp Treatment Kit (Worth $104.00)",
          "papBanner_text": "Save 30%",
          "papPopup_text": "Save 30% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/30.list",
          "visually-hidden": "4.5 Stars 6 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.5,
          "productBlock_reviewCount": 6,
          "productBlock_priceValue": "$63.00",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$90.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/slip-exclusive-silk-caramel-pillowcase-duo-and-delicates-bag/12712935.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/1600/1600/12712935-7654809797324859.jpg",
          "productBlock_productName": "Slip Dermstore Exclusive Silk Caramel Pillowcase Duo and Delicates Bag (Worth $193.00)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$178.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/colorescience-dermstore-exclusive-make-it-matte-set-2-piece/13126486.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13126486-7874866316435176.jpg",
          "productBlock_productName": "Colorescience Dermstore Exclusive Make It Matte Set 2 piece - $195 Value",
          "papBanner_text": "Save 30%",
          "papPopup_text": "Save 30% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/30.list",
          "visually-hidden": "3.25 Stars 4 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 3.25,
          "productBlock_reviewCount": 4,
          "productBlock_priceValue": "$101.50",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$145.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/elemis-dermstore-exclusive-elemis-peptide-24-7-duo-2-piece/12903058.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12903058-1404864829361585.jpg",
          "productBlock_productName": "ELEMIS Dermstore Exclusive ELEMIS Peptide 24/7 Duo (2 piece - $114 Value)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "4.44 Stars 9 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.44,
          "productBlock_reviewCount": 9,
          "productBlock_priceValue": "$85.50",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/obagi-dermstore-exclusive-pro-c-brightening-set-3-piece/12918951.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12918951-2014871574083472.jpg",
          "productBlock_productName": "Obagi Dermstore Exclusive Pro-C Brightening Set 3 piece - $263 Value",
          "papBanner_text": "Save 30%",
          "papPopup_text": "Save 30% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/30.list",
          "visually-hidden": "4.2 Stars 5 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.2,
          "productBlock_reviewCount": 5,
          "productBlock_priceValue": "$156.80",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$224.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/pmd-dermstore-exclusive-personal-microderm-elite-pro-with-masks-1-kit/13166457.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13166457-1014873881454890.jpg",
          "productBlock_productName": "PMD Dermstore Exclusive Personal Microderm Elite Pro with Masks - $339 Value",
          "papBanner_text": "Save 20%",
          "papPopup_text": "Save 20% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/20.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$239.20",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$299.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/naturopathica-dermstore-exclusive-amethyst-peace-mask-1.69-fl.-oz./13166452.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13166452-2064873585324572.jpg",
          "productBlock_productName": "Naturopathica Dermstore Exclusive Amethyst Peace Mask 1.69 fl. oz.",
          "papBanner_text": "$68 Naturopathica Gift",
          "papPopup_text": "Receive a Naturopathica Travel Set ($68 value) when you spend $85 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/naturopathica.list",
          "visually-hidden": "4.5 Stars 2 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 4.5,
          "productBlock_reviewCount": 2,
          "productBlock_priceValue": "$48.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/slip-exclusive-silk-pink-pillowcase-duo-and-delicates-bag/12712938.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/1600/1600/12712938-3884809794576832.jpg",
          "productBlock_productName": "Slip Dermstore Exclusive Silk Pink Pillowcase Duo and Delicates Bag (Worth $193.00)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$178.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/slip-exclusive-silk-marble-pillowcase-duo-and-delicates-bag/12712933.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/1600/1600/12712933-1664809797202366.jpg",
          "productBlock_productName": "Slip Dermstore Exclusive Silk Marble Pillowcase Duo and Delicates Bag (Worth $193.00)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$178.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/espa-retail-detox-and-energise-body-duo-dermstore-exclusive/13887923.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13887923-1534966084706970.jpg",
          "productBlock_productName": "ESPA Detox and Energize Body Duo - Dermstore Exclusive (Worth $155.00)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$109.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/espa-retail-lip-and-hand-hydration-dermstore-exclusive/13887924.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13887924-1874966083821562.jpg",
          "productBlock_productName": "ESPA Lip and Hand Hydration - Dermstore Exclusive (Worth $70.00)",
          "papBanner_text": "Dermstore Exclusive",
          "papPopup_text": "This product is exclusive to Dermstore - a one-of-a-kind available nowhere else. Limited quantity available.",
          "papPopup_link": "VIEW ALL EXCLUSIVES",
          "papPopup_link href": "https://www.dermstore.com/dermstore-exclusives.list",
          "visually-hidden": "",
          "productBlock_ratingStars href": "",
          "productBlock_ratingValue": null,
          "productBlock_reviewCount": null,
          "productBlock_priceValue": "$49.00",
          "productBlock_rrpLabel": "",
          "productBlock_rrpValue": ""
        },
        {
          "productBlock_link href": "https://www.dermstore.com/colorescience-dermstore-exclusive-lit-from-within-set-2-piece/13126485.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13126485-8394866316395027.jpg",
          "productBlock_productName": "Colorescience Dermstore Exclusive Lit From Within Set 2 piece - $223 Value",
          "papBanner_text": "Save 30%",
          "papPopup_text": "Save 30% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/30.list",
          "visually-hidden": "5.0 Stars 3 Reviews",
          "productBlock_ratingStars href": "[object Object]",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 3,
          "productBlock_priceValue": "$117.60",
          "productBlock_rrpLabel": "MSRP:",
          "productBlock_rrpValue": "$168.00"
        }
       ];
export const bestSellerCarousel=[
        {
          "productBlock_link href": "https://www.dermstore.com/skinceuticals-c-e-ferulic-with-15-l-ascorbic-acid-vitamin-c-serum-30ml/11289609.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289609-1174892770940184.jpg",
          "productBlock_productName": "SkinCeuticals C E Ferulic (1 fl. oz.)",
          "papBanner_text": "$13 SkinCeuticals Gift",
          "papPopup_text": "Receive a SkinCeuticals Hyaluronic Acid Intensifier 4ml ($13 value) when you spend $175 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/skinceuticals.list",
          "visually-hidden": "4.75 Stars 4819 Reviews",
          "productBlock_ratingValue": 4.75,
          "productBlock_reviewCount": 4819,
          "productBlock_priceValue": "$169.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/eltamd-uv-clear-broad-spectrum-spf46/11370303.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11370303-1074944341868735.jpg",
          "productBlock_productName": "EltaMD UV Clear Broad-Spectrum SPF 46 (1.7 oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.79 Stars 4715 Reviews",
          "productBlock_ratingValue": 4.79,
          "productBlock_reviewCount": 4715,
          "productBlock_priceValue": "$39.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-tns-advanced-serum-1oz/12596429.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12596429-3594871019700125.jpg",
          "productBlock_productName": "SkinMedica TNS Advanced+ Serum (1 oz.)",
          "papBanner_text": "Save 20%",
          "papPopup_text": "Save 20% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/20.list",
          "visually-hidden": "4.58 Stars 301 Reviews",
          "productBlock_ratingValue": 4.58,
          "productBlock_reviewCount": 301,
          "productBlock_priceValue": "$236.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/beauty-box/best-of-dermstore-the-necessities-kit-431-value/13812005.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13812005-4724980887145978.jpg",
          "productBlock_productName": "Best of Dermstore The Necessities Kit - $431 Value",
          "papBanner_text": "Up to 65% Savings on Best of Dermstore",
          "papPopup_text": "Save up to 65% on Best of Dermstore kits. While stock lasts.",
          "papPopup_link": "SHOP ALL",
          "papPopup_link href": "https://www.dermstore.com/brands/best-of-dermstore.list",
          "visually-hidden": "5.0 Stars 8 Reviews",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 8,
          "productBlock_priceValue": "$100.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/obagi-medical-professional-c-serum-20-strength/11291543.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11291543-1265002181700054.jpg",
          "productBlock_productName": "Obagi Medical Professional-C Serum 20% (1 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.73 Stars 924 Reviews",
          "productBlock_ratingValue": 4.73,
          "productBlock_reviewCount": 924,
          "productBlock_priceValue": "$136.99"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/neocutis-lumiere-firm-riche-extra-moisturizing-illuminating-and-tightening-eye-cream-15ml/12664555.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12664555-1704871739992403.jpg",
          "productBlock_productName": "Neocutis LUMIÈRE® FIRM RICHE Extra Moisturizing Illuminating Tightening Eye Cream (0.5 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.67 Stars 106 Reviews",
          "productBlock_ratingValue": 4.67,
          "productBlock_reviewCount": 106,
          "productBlock_priceValue": "$118.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/is-clinical-active-serum-30ml/11291956.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11291956-2074871578544985.jpg",
          "productBlock_productName": "iS Clinical Active Serum (1 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.64 Stars 476 Reviews",
          "productBlock_ratingValue": 4.64,
          "productBlock_reviewCount": 476,
          "productBlock_priceValue": "$142.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/sunday-riley-good-genes-all-in-one-lactic-acid-treatment-1.7oz/11588281.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11588281-8764882139037003.jpg",
          "productBlock_productName": "Sunday Riley GOOD GENES All-In-One Lactic Acid Treatment (1.7oz. - $175 Value)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.64 Stars 689 Reviews",
          "productBlock_ratingValue": 4.64,
          "productBlock_reviewCount": 689,
          "productBlock_priceValue": "$122.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinceuticals-triple-lipid-restore-2-4-2/11290635.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11290635-1804892767902966.jpg",
          "productBlock_productName": "SkinCeuticals Triple Lipid Restore 242 (1.6 fl. oz.)",
          "papBanner_text": "$13 SkinCeuticals Gift",
          "papPopup_text": "Receive a SkinCeuticals Hyaluronic Acid Intensifier 4ml ($13 value) when you spend $175 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/skinceuticals.list",
          "visually-hidden": "4.8 Stars 1886 Reviews",
          "productBlock_ratingValue": 4.8,
          "productBlock_reviewCount": 1886,
          "productBlock_priceValue": "$136.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/eltamd-uv-clear-tinted-broad-spectrum-spf46/11370312.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11370312-1044938634157826.jpg",
          "productBlock_productName": "EltaMD UV Clear Broad-Spectrum SPF 46 - Tinted (1.7 oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.72 Stars 1314 Reviews",
          "productBlock_ratingValue": 4.72,
          "productBlock_reviewCount": 1314,
          "productBlock_priceValue": "$41.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/pca-skin-hyaluronic-acid-boosting-serum/11429291.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11429291-5004872074831463.jpg",
          "productBlock_productName": "PCA SKIN Hyaluronic Acid Boosting Serum (1 oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.75 Stars 266 Reviews",
          "productBlock_ratingValue": 4.75,
          "productBlock_reviewCount": 266,
          "productBlock_priceValue": "$120.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/revitabrow-advanced-eyebrow-conditioner-3ml/10560418.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/10560418-1514911743023953.jpg",
          "productBlock_productName": "RevitaLash RevitaBrow Advanced Eyebrow Conditioner - 4 Month Supply (0.101 fl. oz.)",
          "papBanner_text": "$15 RevitaLash Gift",
          "papPopup_text": "Receive a RevitaLash Double Ended Volume Set Mascara Deluxe Sample ($15 value) when you spend $125 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/revitalash-cosmetics.list",
          "visually-hidden": "4.65 Stars 237 Reviews",
          "productBlock_ratingValue": 4.65,
          "productBlock_reviewCount": 237,
          "productBlock_priceValue": "$110.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/revision-skincare-d.e.j-eye-cream-0.5-oz./12902717.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13339906-1564915031255922.jpg",
          "productBlock_productName": "Revision Skincare® D.E.J eye cream 0.5 oz.",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.61 Stars 166 Reviews",
          "productBlock_ratingValue": 4.61,
          "productBlock_reviewCount": 166,
          "productBlock_priceValue": "$114.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/paula-s-choice-skin-perfecting-2-bha-liquid-exfoliant-118ml/11174178.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11174178-1044909106371632.jpg",
          "productBlock_productName": "Paula's Choice SKIN PERFECTING 2 BHA Liquid Exfoliant (4 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.66 Stars 742 Reviews",
          "productBlock_ratingValue": 4.66,
          "productBlock_reviewCount": 742,
          "productBlock_priceValue": "$34.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/dr-dennis-gross-alpha-beta-universal-daily-peel-60-pack/13156807.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13156807-2034893783165696.jpg",
          "productBlock_productName": "Dr Dennis Gross Alpha Beta Universal Daily Peel (60 Pack, Worth $204)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.93 Stars 14 Reviews",
          "productBlock_ratingValue": 4.93,
          "productBlock_reviewCount": 14,
          "productBlock_priceValue": "$150.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/avene-professional-retrinal-0.1-cream/11286350.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11286350-1704996952153772.jpg",
          "productBlock_productName": "Avene Retrinal 0.1 Intensive Cream (1.01 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.59 Stars 227 Reviews",
          "productBlock_ratingValue": 4.59,
          "productBlock_reviewCount": 227,
          "productBlock_priceValue": "$74.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/oribe-gold-lust-repair-restore-shampoo-8.5-fl.-oz./12915557.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12915557-2954917112863726.jpg",
          "productBlock_productName": "Oribe Gold Lust Repair Restore Shampoo (8.5 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.72 Stars 183 Reviews",
          "productBlock_ratingValue": 4.72,
          "productBlock_reviewCount": 183,
          "productBlock_priceValue": "$49.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/jan-marini-skin-care-management-system-normal-combo/11379755.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11379755-7624870995301698.jpg",
          "productBlock_productName": "Jan Marini Skin Care Management System - Normal to Combination (5 piece - $374 Value)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.87 Stars 38 Reviews",
          "productBlock_ratingValue": 4.87,
          "productBlock_reviewCount": 38,
          "productBlock_priceValue": "$320.00"
        }
       ];
export const newArrivalsCarousel=[
        {
          "productBlock_link href": "https://www.dermstore.com/skinceuticals-c-e-ferulic-with-15-l-ascorbic-acid-vitamin-c-serum-30ml/11289609.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11289609-1174892770940184.jpg",
          "productBlock_productName": "SkinCeuticals C E Ferulic (1 fl. oz.)",
          "papBanner_text": "$13 SkinCeuticals Gift",
          "papPopup_text": "Receive a SkinCeuticals Hyaluronic Acid Intensifier 4ml ($13 value) when you spend $175 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/skinceuticals.list",
          "visually-hidden": "4.75 Stars 4820 Reviews",
          "productBlock_ratingValue": 4.75,
          "productBlock_reviewCount": 4820,
          "productBlock_priceValue": "$169.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/eltamd-uv-clear-broad-spectrum-spf46/11370303.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11370303-1074944341868735.jpg",
          "productBlock_productName": "EltaMD UV Clear Broad-Spectrum SPF 46 (1.7 oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.79 Stars 4715 Reviews",
          "productBlock_ratingValue": 4.79,
          "productBlock_reviewCount": 4715,
          "productBlock_priceValue": "$39.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinmedica-tns-advanced-serum-1oz/12596429.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12596429-3594871019700125.jpg",
          "productBlock_productName": "SkinMedica TNS Advanced+ Serum (1 oz.)",
          "papBanner_text": "Save 20%",
          "papPopup_text": "Save 20% on select products. Discount automatically applied. Offer valid for a limited time only.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/offers/auto/20.list",
          "visually-hidden": "4.58 Stars 301 Reviews",
          "productBlock_ratingValue": 4.58,
          "productBlock_reviewCount": 301,
          "productBlock_priceValue": "$236.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/beauty-box/best-of-dermstore-the-necessities-kit-431-value/13812005.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13812005-4724980887145978.jpg",
          "productBlock_productName": "Best of Dermstore The Necessities Kit - $431 Value",
          "papBanner_text": "Up to 65% Savings on Best of Dermstore",
          "papPopup_text": "Save up to 65% on Best of Dermstore kits. While stock lasts.",
          "papPopup_link": "SHOP ALL",
          "papPopup_link href": "https://www.dermstore.com/brands/best-of-dermstore.list",
          "visually-hidden": "5.0 Stars 8 Reviews",
          "productBlock_ratingValue": 5,
          "productBlock_reviewCount": 8,
          "productBlock_priceValue": "$100.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/obagi-medical-professional-c-serum-20-strength/11291543.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11291543-1265002181700054.jpg",
          "productBlock_productName": "Obagi Medical Professional-C Serum 20% (1 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.73 Stars 924 Reviews",
          "productBlock_ratingValue": 4.73,
          "productBlock_reviewCount": 924,
          "productBlock_priceValue": "$136.99"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/neocutis-lumiere-firm-riche-extra-moisturizing-illuminating-and-tightening-eye-cream-15ml/12664555.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12664555-1704871739992403.jpg",
          "productBlock_productName": "Neocutis LUMIÈRE® FIRM RICHE Extra Moisturizing Illuminating Tightening Eye Cream (0.5 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.67 Stars 106 Reviews",
          "productBlock_ratingValue": 4.67,
          "productBlock_reviewCount": 106,
          "productBlock_priceValue": "$118.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/is-clinical-active-serum-30ml/11291956.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11291956-2074871578544985.jpg",
          "productBlock_productName": "iS Clinical Active Serum (1 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.64 Stars 476 Reviews",
          "productBlock_ratingValue": 4.64,
          "productBlock_reviewCount": 476,
          "productBlock_priceValue": "$142.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/sunday-riley-good-genes-all-in-one-lactic-acid-treatment-1.7oz/11588281.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11588281-8764882139037003.jpg",
          "productBlock_productName": "Sunday Riley GOOD GENES All-In-One Lactic Acid Treatment (1.7oz. - $175 Value)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.64 Stars 689 Reviews",
          "productBlock_ratingValue": 4.64,
          "productBlock_reviewCount": 689,
          "productBlock_priceValue": "$122.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/skinceuticals-triple-lipid-restore-2-4-2/11290635.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11290635-1804892767902966.jpg",
          "productBlock_productName": "SkinCeuticals Triple Lipid Restore 242 (1.6 fl. oz.)",
          "papBanner_text": "$13 SkinCeuticals Gift",
          "papPopup_text": "Receive a SkinCeuticals Hyaluronic Acid Intensifier 4ml ($13 value) when you spend $175 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/skinceuticals.list",
          "visually-hidden": "4.8 Stars 1886 Reviews",
          "productBlock_ratingValue": 4.8,
          "productBlock_reviewCount": 1886,
          "productBlock_priceValue": "$136.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/eltamd-uv-clear-tinted-broad-spectrum-spf46/11370312.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11370312-1044938634157826.jpg",
          "productBlock_productName": "EltaMD UV Clear Broad-Spectrum SPF 46 - Tinted (1.7 oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.72 Stars 1314 Reviews",
          "productBlock_ratingValue": 4.72,
          "productBlock_reviewCount": 1314,
          "productBlock_priceValue": "$41.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/pca-skin-hyaluronic-acid-boosting-serum/11429291.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11429291-5004872074831463.jpg",
          "productBlock_productName": "PCA SKIN Hyaluronic Acid Boosting Serum (1 oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.75 Stars 266 Reviews",
          "productBlock_ratingValue": 4.75,
          "productBlock_reviewCount": 266,
          "productBlock_priceValue": "$120.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/revitabrow-advanced-eyebrow-conditioner-3ml/10560418.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/10560418-1514911743023953.jpg",
          "productBlock_productName": "RevitaLash RevitaBrow Advanced Eyebrow Conditioner - 4 Month Supply (0.101 fl. oz.)",
          "papBanner_text": "$15 RevitaLash Gift",
          "papPopup_text": "Receive a RevitaLash Double Ended Volume Set Mascara Deluxe Sample ($15 value) when you spend $125 or more on the brand. Complimentary gift will be awarded at the cart. Offer valid limited time only, while supplies last.",
          "papPopup_link": "SHOP NOW",
          "papPopup_link href": "https://www.dermstore.com/brands/revitalash-cosmetics.list",
          "visually-hidden": "4.65 Stars 237 Reviews",
          "productBlock_ratingValue": 4.65,
          "productBlock_reviewCount": 237,
          "productBlock_priceValue": "$110.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/revision-skincare-d.e.j-eye-cream-0.5-oz./12902717.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13339906-1564915031255922.jpg",
          "productBlock_productName": "Revision Skincare® D.E.J eye cream 0.5 oz.",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.61 Stars 166 Reviews",
          "productBlock_ratingValue": 4.61,
          "productBlock_reviewCount": 166,
          "productBlock_priceValue": "$114.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/paula-s-choice-skin-perfecting-2-bha-liquid-exfoliant-118ml/11174178.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11174178-1044909106371632.jpg",
          "productBlock_productName": "Paula's Choice SKIN PERFECTING 2 BHA Liquid Exfoliant (4 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.66 Stars 742 Reviews",
          "productBlock_ratingValue": 4.66,
          "productBlock_reviewCount": 742,
          "productBlock_priceValue": "$34.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/dr-dennis-gross-alpha-beta-universal-daily-peel-60-pack/13156807.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/13156807-2034893783165696.jpg",
          "productBlock_productName": "Dr Dennis Gross Alpha Beta Universal Daily Peel (60 Pack, Worth $204)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.93 Stars 14 Reviews",
          "productBlock_ratingValue": 4.93,
          "productBlock_reviewCount": 14,
          "productBlock_priceValue": "$150.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/avene-professional-retrinal-0.1-cream/11286350.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11286350-1704996952153772.jpg",
          "productBlock_productName": "Avene Retrinal 0.1 Intensive Cream (1.01 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.59 Stars 227 Reviews",
          "productBlock_ratingValue": 4.59,
          "productBlock_reviewCount": 227,
          "productBlock_priceValue": "$74.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/oribe-gold-lust-repair-restore-shampoo-8.5-fl.-oz./12915557.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/12915557-2954917112863726.jpg",
          "productBlock_productName": "Oribe Gold Lust Repair Restore Shampoo (8.5 fl. oz.)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.72 Stars 183 Reviews",
          "productBlock_ratingValue": 4.72,
          "productBlock_reviewCount": 183,
          "productBlock_priceValue": "$49.00"
        },
        {
          "productBlock_link href": "https://www.dermstore.com/jan-marini-skin-care-management-system-normal-combo/11379755.html",
          "productBlock_image src": "https://static.thcdn.com/images/small/webp//productimg/original/11379755-7624870995301698.jpg",
          "productBlock_productName": "Jan Marini Skin Care Management System - Normal to Combination (5 piece - $374 Value)",
          "papBanner_text": "",
          "papPopup_text": "",
          "papPopup_link": "",
          "papPopup_link href": "",
          "visually-hidden": "4.87 Stars 38 Reviews",
          "productBlock_ratingValue": 4.87,
          "productBlock_reviewCount": 38,
          "productBlock_priceValue": "$320.00"
        }
       ];
