export const GET_ONE_PRODUCT = 'ADMIN_PRODUCTS/GET_ONE_PRODUCT';
export const EDIT_PRODUCT_DETAILS = 'ADMIN_PRODUCTS/EDIT_PRODUCT_DETAILS';
export const GET_SINGLE_PURCHASED_ITEM = 'ADMIN_PRODUCTS/GET_SINGLE_PURCHASED_ITEM'